#%RAML 1.0 Library
usage: |
  This library defines some ressource types that are common for Tönnies webservices.
uses:
  ci1764-responses: ci1764ResponseTraits.raml
  
resourceTypes: 
  RESTFul:
    description: |
      ResourceType that defines that this endpoint returns a list of items with name <<resourcePathName | !uppercamelcase | !singularize>>.
      The name of the resource is derived from the name of the endpoint!
    usage: Apply this resource type only to endpoints of the scheme /<item>s/.
    get:
      is: [ ci1764-responses.itemListResponder: { item: <<resourcePathName | !uppercamelcase | !singularize>> } ]
    post:
      is: [ ci1764-responses.itemCreationResponder: { item: <<resourcePathName | !uppercamelcase | !singularize>> } ]
  RESTfulID:
    description: |
      ResourceType that defines that this endpoint returns only one item of a resource with name <<resourcePathName | !uppercamelcase | !singularize>>.
      The name of the resource is derived from the name of the endpoint!
    usage: Apply this resource type only to endpoints of the scheme /<item>s/{ID}.
    get:
      is: [ ci1764-responses.itemResponder: { item: <<resourcePathName | !uppercamelcase | !singularize>> } ]
    put:
      is: [ ci1764-responses.itemResponder: { item: <<resourcePathName | !uppercamelcase | !singularize>> } ]
    delete:
      is: [ ci1764-responses.itemResponder: { item: <<resourcePathName | !uppercamelcase | !singularize>> } ]
  RESTful-ReadOnly:
    description: |
      ResourceType that defines that this endpoint returns a list of items with name <<resourcePathName | !uppercamelcase | !singularize>>.
      The name of the resource is derived from the name of the endpoint!
      This resource type only defines the get-method. Therefore, it's called 'read only'.
    usage: Apply this resource type only to endpoints of the scheme /<item>s/.
    get:
      is: [ ci1764-responses.itemListResponder: { item: <<resourcePathName | !uppercamelcase | !singularize>> } ]
  RESTfulID-ReadOnly:
    description: |
      ResourceType that defines that this endpoint returns only one item of a resource with name <<resourcePathName | !uppercamelcase | !singularize>>.
      The name of the resource is derived from the name of the endpoint!
      This resource type only defines the get-method. Therefore, it's called 'read only'.
    usage: Apply this resource type only to endpoints of the scheme /<item>s/{ID}.
    get:
      is: [ ci1764-responses.itemResponder: { item: <<resourcePathName | !uppercamelcase | !singularize>> } ]
