#%RAML 1.0 Library
usage: |
  This library defines some types that are common for Toennies webservices

types:
   Phone:
      properties:
       type:
         enum: [ WORK, WORK_MOBILE, HOME, HOME_MOBILE, SKYPE ]
         description:  Every type can be defined several times.
       number:
           type: string
           maxLength: 40
           pattern: '^\+\d{2}(?: \d+)(?: [0-9\-]+)$'

   Address:
     properties:
      type:
         enum: [ MAIN, SECONDARY ]  
         description: Person can have several addresses - that are only private ones 
                      Company can have several addresses
      street: 
         type: string [] 
      postalCode: 
         type: string
      city: 
         type: string
      county:
         type: string
      country: 
         type: string
   EmailAddress:
      type: string 
      maxLength: 70
      description: Email-address of an employee
