#%RAML 1.0
title: PS Employee Service
baseUri: https://{env}.toennies.net/ci1802wf/{version}/
baseUriParameters:
  env:
    enum:  [esb, esb-staging, esb-dev]
    description: The environment parameter. Valid is only one of the specified names.
version: v1
protocols: HTTPS
uses:
  ci1764-resourceTypes: ci1764ResourceTypes.raml
  ci1764-responses: ci1764ResponseTraits.raml
  ci1764-traits: ci1764EndpointTraits.raml
  ci1764-types: ci1764Types.raml

types:
  Employee:
    properties:
      key:
        type: string
        required: true
        description: |
          this id should be from type MAIN
          actualy there are one possible. Using ci1792ws -> the key will shown like this:  ci1792ws_(id)
      ids:
        type: ID []
        description: Used to retrieve all Ids of an employee
        required: false
      gender:
        enum: [FEMALE, MALE]
      title:
        type: string
        required: false
        example: DR.
      firstName:
        type: string
        required: true
      lastName:
        type: string
        required: true
      fullName:
        type: string
        description: Composition of "<lastName>, <firstName> <title>"
        example: Mueller, Martin Dr
      type:
        required: true
        enum: [ POI, EXTERN, INTERN]
        description: |
          Employees that belong to other companies, these employees are marked as EXTERN.
          Employees from our company are marked as INTERN. Any other are marked as POI.
          INTERN is equals INT in database
          EXTERN is equlas EXT in database
          POI in spec is equals POI in database - POI = Person Of Interest
      status: 
         enum: [ INACTIVE, ACTIVE ]  
         description: use hrStatus (ci1792ws) for the status.
      alias:
        type: string
        required: false
        description: |
          Alias of active directory account of an employee, this property will be used to login on the systems of toennies
      emailAddresses:
        type: ci1764-types.EmailAddress []
        description: emails they are used inside company
      phones:
        type: ci1764-types.Phone []
        description: phones they are used inside company
      costCenters: 
        type: string []
        description: E.g ["ci1799ws_1211326", "ci1799ws_121156"]
      lastChangedDate:
        type: datetime
        format: rfc3339
        description:  the last time of the update of the table. 
  ID:
    properties:
      type:
        enum: [ MAIN, SECONDARY ]
      number:
        type: string


/employees:
  #type: ci1764-resourceTypes.RESTful-ReadOnly
  get:
    is: [ ci1764-responses.itemListResponder: { item: Employee }, ci1764-traits.orderable, ci1764-traits.paged, ci1764-traits.timedQueryable ]
  description: Retrieve all Employees. 
  /{key}:
    #type: ci1764-resourceTypes.RESTfulID-ReadOnly  
    get:
      is: [ ci1764-responses.itemResponder: { item: Employee } ]  
    description: The key is used to retrieve Employee for that specific id. 

  /active:
    #type: ci1764-resourceTypes.RESTful-ReadOnly
    get:
      is: [ ci1764-responses.itemListResponder: { item: Employee }, ci1764-traits.orderable, ci1764-traits.paged, ci1764-traits.timedQueryable ]
    description: List of active employees (filtered by hrStatus=ACTIVE). Orderable by any attribute. timedQueryable only by lastChangedDate.
  /search:
    #type: ci1764-resourceTypes.RESTful-ReadOnly
    get:
      is: [ ci1764-responses.itemListResponder: { item: Employee }, ci1764-traits.orderable, ci1764-traits.paged, ci1764-traits.timedQueryable ]
